services:

    view_factory:
        class: Shopery\View\Factory\RootViewFactory
        public: false
        calls:
            - [ setFactory, [ "@view_factory.composite" ] ]

    view_factory.composite:
        class: Shopery\View\Factory\CompositeViewFactory
        public: false
        arguments:
            - [ "@view_factory.registry", "@view_factory.collection" ]

    view_factory.registry:
        class: Shopery\View\Factory\RegistryViewFactory
        public: false

    view_factory.collection:
        class: Shopery\View\Factory\CollectionViewFactory
        public: false

    view_factory.extension:
        class: Shopery\View\Extension\ExtensibleViewFactory
        public: false
        decorates: view_factory.registry
        arguments:
            - "@view_factory.extension.inner"
            - "@view_factory.extension_resolver"

    view_factory.extension_resolver:
        class: Shopery\Bundle\ViewBundle\Resolver\SymfonyExtensionViewResolver
        public: false
        arguments:
            - "@service_container"
